name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs at every 9AM JST

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SYMBOL_VERSION: "3"
